name: trashman
description: Tells you when to put the bins out.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  tuple: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0
  flutter_native_splash: ^1.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/android_legacy.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/android_adaptive_foreground.png"

flutter_app_name:
  name: "Trashman"

flutter_native_splash:
  background_image: assets/splash/background.png
  image: assets/splash/foreground.png
  android12: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/